package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "physics",
#    srcs = ["rigidbody.cpp"],
#    hdrs = ["rigidbody.h"],
#    deps = ["//src/engine:engine"]
#)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    )
)
