package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "math",
#    srcs = ["vector3.cpp"],
#    hdrs = ["vector3.h"]
#)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    )
)
