package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "flapper",
#    srcs = ["flapper.cpp"],
#    hdrs = ["flapper.h"],
#    deps = ["//src/engine/graphics:graphics"]
#)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    )
)
