package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "engine",
#    srcs = ["engine.cpp"],
#    hdrs = ["engine.h"]
#)


filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    )
)
