package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "graphics",
#    srcs = [
#        "sprite.cpp",
#        "texture.cpp"
#    ],
#    hdrs = [
#        "sprite.h",
#        "texture.h"
#    ]
#)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    )
)
